### ISSUE TITLE
Include HTTP-Verb in Output

### ISSUE THREAD

**Issue by ghandmann** [kobake/AspNetCore.RouteAnalyzer#13]
Hi there,
just installed you package and really like the output so far. But i would be cool if you could include the HTTP Verb (if specified) for a route.

Just a small improvement proposal. :)

Best regards
Sven

**Comment by kobake** [comment]
@ghandmann 
Thank you for your report! I absolutely agree it.
@nicolaspierre1990 solved this issue on #18.

I'm appreciate the two of you. Thanks again!!! 👍
